### ISSUE TITLE
Ensure Only type title question and answer are necessary for correct generation

### ISSUE THREAD

**Issue by JA-VON** [JA-VON/QGenPY#12]

**Comment by ANich** [comment]
Shouldn't body be necessary as well?

**Comment by JA-VON** [comment]
Yes body should be necessary as well i just forgot

On Tue, Apr 5, 2016, 09:54 ANich <notifications@github.com> wrote:

> Shouldn't body be necessary as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JA-VON/QGenPY/issues/12#issuecomment-205843780>
>
-- 
Regards,


Javon Davis
http://javon.devport.co
https://jm.linkedin.com/in/javon-davis-015b808b
