### ISSUE TITLE
All capability to import external files

### ISSUE THREAD

**Issue by JA-VON** [JA-VON/QGenPY#5]
Users should be able to write their own custom code in external files and either have a method to import it directly into their own template or place it into a repository for third party use.

**Comment by ANich** [comment]
See my last commit (Desperately needs refactoring)

**Comment by JA-VON** [comment]
I made some changes to directory structure and syntax for the imports tag and also some code modifications to the imports because it didn't seem to work when I tried, I got an ImportError. See the imports_dev branch https://github.com/JA-VON/QGenPY/tree/imports_dev

**Comment by JA-VON** [comment]
Resolved in 1ee57f4, @ANich can open back the issue if necessary
